### ISSUE TITLE
Fail to parse complex sentence

### ISSUE THREAD

**Issue by hadifar** [iamrkg31/sentence-to-clauses#1]
Hello, 

First of all, thanks for your code.

I tried the following example and it failed:
`
Despite these accomplishments, he was never fully recognised in his home country during his lifetime due to the prevalence of homophobia at the time and because much of his work was covered by the Official Secrets Act.`

> ['Despite these accomplishments , he was never fully recognised in his home country during his lifetime due to the prevalence of homophobia at the time', 'Despite these accomplishments , he was covered by the Official Secrets Act']

**Comment by rahulkg31** [comment]
Sorry for very late reply. 

Yes, the code works for simple sentence structures only. It will fail to parse complex sentences. Also, it completely depends on the parser we are using, if the parser parses the sentences differently than expected, then it will not work. And the open source parsers are not that accurate when handling complex sentences.

**Comment by rahulkg31** [comment]
Closing for now.
