### ISSUE TITLE
Is it possible to add another subordinate, like conjunction, punct or another custom char?

### ISSUE THREAD

**Issue by asyrofist** [iamrkg31/sentence-to-clauses#2]
This Module is great. That can separate sentence to clause with subordinate, but it is possible to separate by conjunction too..
Because I  try to add CC after S|SBVAR|SBVQ. 
It's always says error messaged List index out of range or  
TypeError: string indices must be integers

**Comment by rahulkg31** [comment]
Hi,

No, the current implementation will not be able to handle such scenarios. It works for simple sentences only and depends entirely on the performance of the parser. The problem you are referring to is a very complex one. You could add more patterns to handle few of these scenarios but this approach would probably not work for most of the cases.

Thanks

**Comment by asyrofist** [comment]
thanks for your response before @rahulkg31 , I have tried another example like this one.
`The product should allow the grid to be oriented by the user. Rotation, zoom and move functions should be employed` 
going to be like this one.
```
The product should allow the grid to be oriented by the user. 
Rotation functions should be employed. 
zoom functions should be employed.
move functions should be employed.
```

but I have tried to modified `flag  `from `def get_pos(t)`  into this
`flag = re.search(r"(S|SBAR|SBARQ|SINV|SQ|CC)", ' '.join(children))`
and then loop your `sub_tree `from `def get_clause_list(sent_tree)` into this

```
    def get_clause_list(self, sent_tree):
        clause_level_list = ["S","SBAR","SBARQ","SINV","SQ", "CC"]
        ....
        for sub_tree in reversed(list(sent_tree.subtrees())):
            if sub_tree.label() in clause_level_list:
                if sub_tree.parent().label() in clause_level_list:
                    continue
                if (len(sub_tree) == 1 and sub_tree.label() == "S" and sub_tree[0].label() == "VP" and sub_tree[0].label() == "CC"
                   ...

```

and then, the error command result say  
`IndexError: list index out of range` - I don't have idea, how it appear.
`TypeError: leaves() takes 1 positional argument but 2 were given` -  another appear, how handle it
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)` - It's comment because I'm using stanfordcorenlp

Did you know how to fix it? I'm so frustated and confused @rahulkg31 I'm also [attach my problem](https://github.com/Lynten/stanford-corenlp/issues/103#issue-1020649481) to creator of stanfordcorenlp  too..

Note: I'm using both pycorenlp and stanfordcorenlp, because i'm using it for a backup. If the corenlp is down, So I can use jar model.
```
  try:
    nlp = pycorenlp.StanfordCoreNLP(url_stanford) # pycorenlp get from website corenlp.run
  except:
    # nlp = StanfordCoreNLP(url_stanford, port= 80) # stanford nlp get from website corenlp.run
    nlp = StanfordCoreNLP(model_stanford) # stanford nlp get from website model

```

**Comment by rahulkg31** [comment]
You can use sentence tokenizer to split the `The product should allow the grid to be oriented by the user. Rotation, zoom and move functions should be employed` into `The product should allow the grid to be oriented by the user.` and `Rotation, zoom and move functions should be employed` and then perform the code on these sentences. But to handle 2nd sentence, you might have to analyze the parse tree and add pattern to the code.

It has been 4 years since I coded this, so I won't be able to help you with code, but you could find out the line that is giving the issue and debug it. You might also have to learn about nltk.tree to know what parameters are allowed. You can't just add anything, you might get index issues.

**Comment by asyrofist** [comment]
Well, thank you before.. I appreciate for your answer. I'll try to find complex sentence pattern soon.
your code will be my reference in [here](https://pypi.org/project/extractreq/).
